name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Needed to write to GitHub draft release

env:
  RPC_VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          msbuild /p:Configuration=Release
      - name: Upload launcher build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: northstar-discord-rpc
          path: |
            x64/Release/*.dll
            x64/Release/*.exe
            x64/Release/*.txt
      - name: Upload debug build artifact
        uses: actions/upload-artifact@v3
        with:
          name: discord-rpc-debug-files
          path: |
            x64/Release/*.pdb
